### ISSUE TITLE
Call to undefined method JoliCode\Harvest\Api\Endpoint\CreateInvoice::getSerializedBody()

### ISSUE THREAD

**Issue by laravelian** [jolicode/harvest-php-api#18]
Steps to reproduce:

$payload = new InvoicePostBody();
$payload->setClientId($clientId);
$invoice = $client->createInvoice($postBody);

**Comment by xavierlacot** [comment]
Hi @laravelian,

Thanks for the feedback. The problem has been fixed in the recent 4.0.1 release, through the upgrade of the janephp dependency. I also added an [invoice creation example](/jolicode/harvest-php-api/blob/master/doc/index.md#create-an-invoice).
