### ISSUE TITLE
Missing data from objects

### ISSUE THREAD

**Issue by adamj88** [jolicode/harvest-php-api#37]
Since upgrading from v4.2.0 to v5.2.0, in instances where API requests return additional objects the full object data is missing, for example:

When calling the `listTimeEntries` and the subsequent API request detailed on the [Harvest Documentation](https://help.getharvest.com/api-v2/timesheets-api/timesheets/time-entries/) there should also be associated entries for:

- [User assignment](https://help.getharvest.com/api-v2/projects-api/projects/user-assignments/#the-user-assignment-object)
- [Task assignment](https://help.getharvest.com/api-v2/projects-api/projects/task-assignments/#the-task-assignment-object)

Whilst there is data present it doesn't conform to the above objects, e.g. for a TimeEntryUser (user assignment) the following is returned:

```
object(JoliCode\Harvest\Api\Model\TimeEntryUser)#4423 (2) {
  ["id":protected]=>
  int(1155867)
  ["name":protected]=>
  string(17) "Firstname Lastname"
}
```

The data returned by the API has much more data, it appears to be limited by: https://github.com/jolicode/harvest-php-api/blob/367c9afe6bc046d7299cdb836fa2f243c74eb080/generated/Model/TimeEntryUser.php

It also happens across other API requests, e.g. `listContacts` returns a shorter user client object.

**Comment by xavierlacot** [comment]
Hi @adamj88!

Thank you for this feedback. I am not sure to understand the issue.

As per the doc, a call to `listTimeEntries` will return a list of time entries (`JoliCode\Harvest\Api\Model\TimeEntry` objects), which have several properties, among them:
 * `user`: An object containing the id and name of the associated user (available as a `JoliCode\Harvest\Api\Model\TimeEntryUser` object in this library)
 * `user_assignment`: A [user assignment object](https://help.getharvest.com/api-v2/projects-api/projects/user-assignments/#the-user-assignment-object) of the associated user (available as a `JoliCode\Harvest\Api\Model\UserAssignment` object in this library)

For example, see the following example code:

```php
<?php

require './vendor/autoload.php';

$accessToken = 'SOME TOKEN HERE';
$harvestAccountId = '12345';

$harvestClient = JoliCode\Harvest\ClientFactory::create(
  $accessToken,
  $harvestAccountId
);

$entries = $harvestClient->listTimeEntries([
])->getTimeEntries();

dump($entries[0]);
```

With the v5.2.0 release, this will output the first time entry, an object of the form:

```
^ JoliCode\Harvest\Api\Model\TimeEntry^ {#89
  #id: 1111222233
  #spentDate: DateTime @1566165600 {#76
    date: 2019-08-19 00:00:00.0 Europe/Berlin (+02:00)
  }
  #user: JoliCode\Harvest\Api\Model\TimeEntryUser^ {#71
    #id: 1234567
    #name: "John Doe"
  }
  #userAssignment: JoliCode\Harvest\Api\Model\UserAssignment^ {#78
    #id: 123456789
    #project: null
    #user: null
    #isActive: true
    #isProjectManager: false
    #useDefaultRates: false
    #hourlyRate: null
    #budget: null
    #createdAt: DateTime @1542616541 {#81
      date: 2018-11-19 09:35:41.0 Europe/Berlin (+01:00)
    }
    #updatedAt: DateTime @1542616541 {#80
      date: 2018-11-19 09:35:41.0 Europe/Berlin (+01:00)
    }
  }
  #client: JoliCode\Harvest\Api\Model\TimeEntryClient^ {#82
    #id: 1234567
    #name: "ACME Inc."
  }
  #project: JoliCode\Harvest\Api\Model\TimeEntryProject^ {#97
    #id: 12345678
    #name: "Some project Name"
  }
  #task: JoliCode\Harvest\Api\Model\TimeEntryTask^ {#100
    #id: 12345678
    #name: "Some task name"
  }
  #taskAssignment: JoliCode\Harvest\Api\Model\TaskAssignment^ {#102
    #id: 234567890
    #project: null
    #task: null
    #isActive: true
    #billable: false
    #hourlyRate: null
    #budget: null
    #createdAt: DateTime @1542616541 {#103
      date: 2018-11-19 09:35:41.0 Europe/Berlin (+01:00)
    }
    #updatedAt: DateTime @1542616541 {#104
      date: 2018-11-19 09:35:41.0 Europe/Berlin (+01:00)
    }
  }
  #externalReference: null
  #invoice: null
  #hours: 4.0
  #hoursWithoutTimer: 4.0
  #roundedHours: 4.0
  #notes: null
  #isLocked: false
  #lockedReason: null
  #isClosed: false
  #isBilled: false
  #timerStartedAt: null
  #startedTime: null
  #endedTime: null
  #isRunning: false
  #billable: false
  #budgeted: false
  #billableRate: null
  #costRate: null
  #createdAt: DateTime @1566821327 {#105
    date: 2019-08-26 14:08:47.0 Europe/Berlin (+02:00)
  }
  #updatedAt: DateTime @1566821327 {#106
    date: 2019-08-26 14:08:47.0 Europe/Berlin (+02:00)
  }
```

These objects are generated based on the API json response body, which is:

```json
{
    "id": 1111222233,
    "spent_date": "2019-08-19",
    "hours": 4.0,
    "hours_without_timer": 4.0,
    "rounded_hours": 4.0,
    "notes": null,
    "is_locked": false,
    "locked_reason": null,
    "is_closed": false,
    "is_billed": false,
    "timer_started_at": null,
    "started_time": null,
    "ended_time": null,
    "is_running": false,
    "billable": false,
    "budgeted": false,
    "billable_rate": null,
    "cost_rate": null,
    "created_at": "2019-08-26T14:08:47Z",
    "updated_at": "2019-08-26T14:08:47Z",
    "user": {
        "id": 1234567,
        "name": "John Doe"
    },
    "client": {
        "id": 1234567,
        "name": "ACME Inc.",
        "currency": "CHF"
    },
    "project": {
        "id": 12345678,
        "name": "Some project name",
        "code": ""
    },
    "task": {
        "id": 12345678,
        "name": "Some task name"
    },
    "user_assignment": {
        "id": 123456789,
        "is_project_manager": false,
        "is_active": true,
        "use_default_rates": false,
        "budget": null,
        "created_at": "2018-11-19T09:35:41Z",
        "updated_at": "2018-11-19T09:35:41Z",
        "hourly_rate": null
    },
    "task_assignment": {
        "id": 234567890,
        "billable": false,
        "is_active": true,
        "created_at": "2018-11-19T09:35:41Z",
        "updated_at": "2018-11-19T09:35:41Z",
        "hourly_rate": null,
        "budget": null
    },
    "invoice": null,
    "external_reference": null
}
```

To summarize, the `user_assignment` json property can be found in the `userAssignment` property in the PHP object.

We can notice that some properties are not deserialized:

 * `client.currency`
 * `project.code`

It is perfectly normal, as these properties are not documented correctly : 

![Capture d’écran de 2022-08-03 16-56-51](https://user-images.githubusercontent.com/177293/182640648-4c229933-ff2f-45f1-85dc-10116b5b306a.png)

(and by the way, these properties do also not appear in the examples provided in the doc). This documentation is [parsed to produce the openapi specification](https://github.com/jolicode/harvest-openapi-generator) - should Harvest fix the doc, it should reflect in the generated openapi spec.

As a sidenote, the output with the release v4.2.0 is exactly similar.

Did I miss something else? :smiley:

**Comment by xavierlacot** [comment]
Hi @adamj88 
I am closing this issue, feel free to -re-open if you have more details to share.
